baseURL = 'https://freddyfernando.github.io/'
languageCode = 'en-us'
title = 'Frederick Fernando'
theme = 'terminal'

[params]
  # dir name of your main content (default is `content/posts`).
  contentTypeName = "posts"
  themeColor = "green"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Frederick Fernando"
    subtitle = "Personal Blog"
    owner = "Frederick Fernando"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Frederick Fernando"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"